{
 "title": "SprintBoot test",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "jvmThreadsStates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "Anthony-Test.jvmThreadsStates.state.*"
    }
   ]
  },
  {
   "title": "m1_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "Anthony-Test.httpServerRequests.*.*.method.GET.*.*.*.*.uri._greeting.m1_rate"
    }
   ]
  },
  {
   "title": "p75, p999, max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "Anthony-Test.httpServerRequests.*.*.*.GET.*.*.*.*.uri._greeting.p75"
    },
    {
     "target": "Anthony-Test.httpServerRequests.*.*.*.GET.*.*.*.*.uri._greeting.p999"
    },
    {
     "target": "Anthony-Test.httpServerRequests.*.*.*.GET.*.*.*.*.uri._greeting.max"
    }
   ]
  }
 ]
}